[package]
name = "android_logger"
version = "0.2.2"
authors = ["The android_logger Developers"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Nercury/android_logger-rs"
description = """
A logging implementation for `log` which hooks to android log output.
"""

[dependencies.log]
version = "0.3"

[dependencies.android_log-sys]
version = "0.1"
